---
version: "3.1"
services:
  grav:
    image: lscr.io/linuxserver/grav:latest
    container_name: grav
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    volumes:
      - ${GRAV_CONFIG_PATH}:/config
    ports:
      - ${HTTP_PORT}:80
    restart: unless-stopped
