---
version: "3.8"
services:
  dashy:
    container_name: Dashy
    image: lissy93/dashy
    volumes:
      - ${DASHY_CONFIG}:/app/public/conf.yml
      - ${DASHY_ICONS}:/app/public/item-icons
    ports:
      - ${DASHY_PORT}:80
    environment:
      NODE_ENV: production
      UID: 1000
      GID: 1000
    restart: unless-stopped

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
